# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alfred Gutierrez
email: alf.g.jr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hello.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alfg.com" # the base hostname & protocol for your site
github_username: alfg
linkedin_profile: http://www.linkedin.com/pub/alfred-gutierrez/58/ba1/93b

# Build settings
markdown: kramdown
